version: '3'
services:
  air-monitor-node-exporter:
    image: tan4ek/clear-grass-air-monitor-node-exporter:latest
    container_name: air-monitor-extractor
    ports:
      - 5433:5433
    volumes:
      - ./config.ini:/app/config.ini