{
 "title": "Air monitor",
 "description": "ClearGrassAirMonitor",
 "tags": [ "home" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "PM25",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_pm25", "legendFormat": "PM25" }
   ]
  },
  {
   "title": "tVOC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_tvoc", "legendFormat": "tVOC" }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "home_battery", "legendFormat": "Battery" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "home_co2", "legendFormat": "CO2" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "home_temperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "home_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "PM25",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    { "expr": "home_pm25", "legendFormat": "PM25" }
   ]
  },
  {
   "title": "tVOC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    { "expr": "home_tvoc", "legendFormat": "tVOC" }
   ]
  }
 ]
}